try {
  console.log('Passing!');
} catch(err) {
  console.log("Fail");
}
